baseURL: http://ohthehugemanatee.github.io
languageCode: en-us
title: Oh The Huge Manatee!
theme: hyde-hyde
disqusShortname: ohthehugemanatee
permalinks:
  blog: blog/:year/:month/:day/:title/

params:
  description: "Thoughts and technical notes from the field. I'm Campbell Vertesi, a principal lead software engineer at Microsoft, opera singer, and parent. These are the things that go through my mind."
  relatedPosts: true
  highlightjs: true
  highlightjsstyle: "solarized-dark"
  social:
    gravatar: "campbell@vertesi.com"
    twitter: "campbellvertesi"
    github: "ohthehugemanatee"
    linkedin: "campbellvertesi"
