baseURL: http://ohthehugemanatee.github.io
languageCode: en-us
title: Oh The Huge Manatee!
theme: hyde-hyde
disqusShortname: ohthehugemanatee
permalinks:
  blog: blog/:year/:month/:day/:slug/

Menus:
  main:
    - Name: "Blog"
      URL: "/"
    - Name: "About Me"
      URL: "/about"

params:
  description: "Thoughts and technical notes from the field. I'm Campbell Vertesi, a principal lead software engineer at Microsoft, opera singer, and parent. These are the things that go through my mind."
  relatedPosts: true
  highlightjs: true
  highlightjsstyle: "solarized-dark"
  authorimage: "/images/oh_the_huge_manatee.png"
  social:
    twitter: "campbellvertesi"
    github: "ohthehugemanatee"
    linkedin: "campbellvertesi"
